name: Mirror this repository to other git server
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirror repository
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_MIRROR }}
          REPO_URL_MIRROR: ${{ secrets.REPO_URL_MIRROR }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git remote add mirror "$REPO_URL_MIRROR"
          git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"
